name:                avix
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/myuon/avix#readme
license:             MIT
author:              myuon
maintainer:          ioi.joi.koi.loi@gmail.com
copyright:           2017 myuon
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - linear
  - bookkeeper
  - lens
  - aeson
  - type-level-sets
  - text

executables:
  avix:
    source-dirs:      src
    main:             Main.hs
