name:                avix
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/myuon/avix#readme
license:             MIT
author:              myuon
maintainer:          ioi.joi.koi.loi@gmail.com
copyright:           2017 myuon
category:            Media
extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- linear
- extensible
- lens
- text
- intervals
- text-format
- ghc-prim

default-extensions:
- Strict
- StrictData
- TemplateHaskell
- DataKinds
- KindSignatures
- TypeOperators
- TypeFamilies
- MultiParamTypeClasses
- FunctionalDependencies
- FlexibleInstances
- LambdaCase
- OverloadedLabels
- TypeApplications
- PolyKinds
- FlexibleContexts
- OverloadedStrings
- ViewPatterns

ghc-options:
- -Wunused-imports
- -Wunused-local-binds

library:
  source-dirs:      src
